### ISSUE TITLE
Is this entire library broken?

### ISSUE THREAD

**Issue by DorianTheGrey** [LukeHagar/plexjs#20]
I am puzzled, has anything changed and has broken this entire library? I tested my token with curl and it works on the same machine, but using even the most basic example (e.g. getServerCapabilities) with the same data gives me the following every time:

```
node:internal/deps/undici/undici:12502
      Error.captureStackTrace(err, this);
            ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HTTPClient.request (/home/jan/plexindex/node_modules/@lukehagar/plexjs/lib/http.js:46:25)
    at async Server.do$ (/home/jan/plexindex/node_modules/@lukehagar/plexjs/lib/sdks.js:84:24)
    at async Server.getServerCapabilities (/home/jan/plexindex/node_modules/@lukehagar/plexjs/sdk/server.js:95:26)
    at async run (file:///home/jan/plexindex/index.js:9:18) {
  [cause]: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:6635:28)
      at node:internal/deps/undici/undici:6587:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:6619:13)
      at process.processImmediate (node:internal/timers:478:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

Node.js v20.15.0

**Comment by LukeHagar** [comment]
Hey Dorian!

Thanks for brining up this issue.

I’ll look into it and circle back with what I find.

**Comment by LukeHagar** [comment]
Can you share what your usage looks like? is this just a simple TS file?

**Comment by DorianTheGrey** [comment]
Hi Luke,

 

Thanks for coming back to me!

 

Sure, my pleasure to share. I attached:

 

1.	Project.png, just a screenshot from the project folder
2.	Index.png, showing you the index.js
3.	Package.png, showing you the package.json content
4.	Ubunturelease.png, just to ensure it’s 22.04 (Node.js is version 20.15.0)
5.	Output.png shows the output with the error by simply running: node index.js
6.	Curl.png shows the working curl result on the same machine with the same token.

 

If I didn’t miss anything that seems like the very basic example on your Github page. Your wrapper looks really great and I would love to be able to use it. Thanks again for having a look!

 

Cheers,

Jan

**Comment by LukeHagar** [comment]
Hey @DorianTheGrey, it looks like the images you tried to attach didn't come through

**Comment by LukeHagar** [comment]
Happy to reopen this if you are able to assist with more information
